version: "3.9"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    command: bash entrypoint.sh
    depends_on:
      - db
      - nats
    ports:
      - "8080:8080"
  db:
    image: postgres:15-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - "5432:5432"
    env_file:
      - .env
  nats:
    image: nats-streaming
    env_file:
      - .env
    ports:
      - "4222:4222"
      - "8222:8222"

volumes:
  postgres_data:
